### ISSUE TITLE
Import database to Metasploit - No script EyeWitness.py

### ISSUE THREAD

**Issue by Q-nu** [BillyV4/ID-entify#1]
#Hi,

Thanks for your great Python script.

For your information I found issues in your python scripts.

1) There is some trace of spanish language when you execute the ID-Entify.py:
> WHAT IS THE DOMINE?: xxxx.yy
> Domine: xxxx.yy
> WHICH IS THE WEBSITE?: www.xxxx.yy
> Website: www.xxxx.yy
> THE FILES WILL BE SAVED IN: 
> /usr/share/ID-entify/RawData/xxxx.yy
> **Completado** 1 de 12

2) Again in the ID-Entify-report.py, question asked twice and answer in spain:
> **Do you want to run nmapdo you want to run NMAP?**
>  1 = **SI**
>  2 = **NO**

3) I get this error when I execute the python script ID-Entify-report.py.

> Importing database to METASPLOIT
> python /usr/share/ID-entify/Programs/EyeWitness.py -f /usr/share/ID-entify/Programs/Information/DNS.txt --web
> **python: can't open file '/usr/share/ID-entify/Programs/EyeWitness.py': [Errno 2] No such file or directory**
> FIN

**Comment by BillyV4** [comment]
I modified the script code and took the opportunity to add some new tools to make the script more friendly, in a later version I will resume the port scan and screenshot.
